title: "MOOC - Matemática"
description: "Materiales de apoyo para el aprendizaje de Matemática"

baseurl: "https://andres-merino.github.io/MOOC-matematica"
url: "https://andres-merino.github.io/MOOC-matematica"